import hashlib
import json
from datetime import timedelta

from django.db import connection
from django.test import TestCase, override_settings
from django.utils import timezone
from rest_framework.test import APIClient


PORTAL_TOKEN = "portal-test-token"
PORTAL_TOKEN_HASH = hashlib.sha256(PORTAL_TOKEN.encode("utf-8")).hexdigest()


@override_settings(
    PORTAL_INTEGRATION_TOKEN_SHA256=PORTAL_TOKEN_HASH,
    PORTAL_INTEGRATION_TOKEN_SHA256_FALLBACKS=[],
    PORTAL_INTEGRATION_ALLOWED_IPS=[],
)
class PortalIntegrationAPITest(TestCase):
    @classmethod
    def setUpClass(cls):
        dt_type = "TIMESTAMPTZ" if connection.vendor == "postgresql" else "DATETIME"
        bool_type = "BOOLEAN" if connection.vendor != "sqlite" else "INTEGER"
        identity_type = "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" if connection.vendor == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
        json_type = "JSONB" if connection.vendor == "postgresql" else "TEXT"

        with connection.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS customers (
                    id INTEGER PRIMARY KEY,
                    razon_social TEXT
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS marcas (
                    id INTEGER PRIMARY KEY,
                    nombre TEXT
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS models (
                    id INTEGER PRIMARY KEY,
                    marca_id INTEGER,
                    nombre TEXT,
                    tipo_equipo TEXT,
                    variante TEXT
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS locations (
                    id INTEGER PRIMARY KEY,
                    nombre TEXT
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY,
                    nombre TEXT,
                    email TEXT,
                    hash_pw TEXT,
                    rol TEXT,
                    activo BOOLEAN
                )
                """.replace("BOOLEAN", bool_type)
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS devices (
                    id INTEGER PRIMARY KEY,
                    customer_id INTEGER,
                    marca_id INTEGER,
                    model_id INTEGER,
                    numero_serie TEXT,
                    numero_interno TEXT,
                    tipo_equipo TEXT,
                    variante TEXT
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS ingresos (
                    id INTEGER PRIMARY KEY,
                    device_id INTEGER,
                    estado TEXT,
                    presupuesto_estado TEXT,
                    motivo TEXT,
                    fecha_ingreso {dt_type},
                    fecha_creacion {dt_type},
                    fecha_servicio {dt_type},
                    ubicacion_id INTEGER,
                    asignado_a INTEGER,
                    equipo_variante TEXT,
                    informe_preliminar TEXT,
                    descripcion_problema TEXT,
                    trabajos_realizados TEXT
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS quotes (
                    id INTEGER PRIMARY KEY,
                    ingreso_id INTEGER,
                    version_num INTEGER NOT NULL DEFAULT 1,
                    origen_quote_id INTEGER NULL,
                    estado TEXT,
                    subtotal NUMERIC,
                    iva_21 NUMERIC,
                    total NUMERIC,
                    moneda TEXT,
                    fecha_emitido {dt_type},
                    fecha_aprobado {dt_type},
                    fecha_rechazado {dt_type},
                    rechazo_comentario TEXT,
                    autorizado_por TEXT,
                    forma_pago TEXT,
                    plazo_entrega_txt TEXT,
                    garantia_txt TEXT,
                    mant_oferta_txt TEXT,
                    pdf_url TEXT
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS quote_items (
                    id INTEGER PRIMARY KEY,
                    quote_id INTEGER,
                    tipo TEXT,
                    descripcion TEXT,
                    qty NUMERIC,
                    precio_u NUMERIC,
                    repuesto_id INTEGER,
                    repuesto_codigo TEXT,
                    costo_u_neto NUMERIC
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS ingreso_tests (
                    ingreso_id INTEGER PRIMARY KEY,
                    template_key TEXT,
                    template_version TEXT,
                    tipo_equipo_snapshot TEXT,
                    payload {json_type},
                    schema_snapshot {json_type},
                    references_snapshot {json_type},
                    resultado_global TEXT,
                    conclusion TEXT,
                    instrumentos TEXT,
                    firmado_por TEXT,
                    fecha_ejecucion {dt_type},
                    tecnico_id INTEGER,
                    created_at {dt_type},
                    updated_at {dt_type}
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS ingreso_events (
                    ingreso_id INTEGER,
                    a_estado TEXT,
                    ts {dt_type}
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS ingreso_media (
                    id {identity_type},
                    ingreso_id INTEGER,
                    usuario_id INTEGER,
                    comentario TEXT,
                    mime_type TEXT,
                    size_bytes INTEGER,
                    width INTEGER,
                    height INTEGER,
                    original_name TEXT,
                    storage_path TEXT,
                    thumbnail_path TEXT,
                    created_at {dt_type},
                    updated_at {dt_type}
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS notifications (
                    id {identity_type},
                    user_id INTEGER,
                    notification_key TEXT,
                    dedupe_key TEXT,
                    title TEXT,
                    body TEXT,
                    href TEXT,
                    severity TEXT,
                    entity_type TEXT,
                    entity_id TEXT,
                    payload {json_type},
                    created_at {dt_type} DEFAULT CURRENT_TIMESTAMP,
                    clicked_at {dt_type}
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS notification_user_preferences (
                    id {identity_type},
                    user_id INTEGER NOT NULL,
                    notification_key TEXT NOT NULL,
                    enabled BOOLEAN NULL
                )
                """.replace("BOOLEAN", bool_type)
            )
            cur.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_user_key_dedupe
                ON notifications(user_id, notification_key, dedupe_key)
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS equipos_derivados (
                    id INTEGER PRIMARY KEY,
                    ingreso_id INTEGER,
                    estado TEXT,
                    fecha_deriv {dt_type}
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS bejerman_article_mappings (
                    id INTEGER PRIMARY KEY,
                    model_id INTEGER NOT NULL,
                    variante TEXT NOT NULL DEFAULT '',
                    variante_norm TEXT NOT NULL DEFAULT '',
                    article_code TEXT NOT NULL,
                    article_description TEXT NULL,
                    match_source TEXT NOT NULL DEFAULT 'manual'
                )
                """
            )
            for ddl in (
                "ALTER TABLE customers ADD COLUMN IF NOT EXISTS razon_social TEXT",
                "ALTER TABLE marcas ADD COLUMN IF NOT EXISTS nombre TEXT",
                "ALTER TABLE models ADD COLUMN IF NOT EXISTS marca_id INTEGER",
                "ALTER TABLE models ADD COLUMN IF NOT EXISTS nombre TEXT",
                "ALTER TABLE models ADD COLUMN IF NOT EXISTS tipo_equipo TEXT",
                "ALTER TABLE models ADD COLUMN IF NOT EXISTS variante TEXT",
                "ALTER TABLE devices ADD COLUMN IF NOT EXISTS customer_id INTEGER",
                "ALTER TABLE devices ADD COLUMN IF NOT EXISTS marca_id INTEGER",
                "ALTER TABLE devices ADD COLUMN IF NOT EXISTS model_id INTEGER",
                "ALTER TABLE devices ADD COLUMN IF NOT EXISTS numero_serie TEXT",
                "ALTER TABLE devices ADD COLUMN IF NOT EXISTS numero_interno TEXT",
                "ALTER TABLE devices ADD COLUMN IF NOT EXISTS tipo_equipo TEXT",
                "ALTER TABLE devices ADD COLUMN IF NOT EXISTS variante TEXT",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS presupuesto_estado TEXT",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS resolucion TEXT",
                f"ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS fecha_ingreso {dt_type}",
                f"ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS fecha_creacion {dt_type}",
                f"ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS fecha_servicio {dt_type}",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS ubicacion_id INTEGER",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS asignado_a INTEGER",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS equipo_variante TEXT",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS informe_preliminar TEXT",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS descripcion_problema TEXT",
                "ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS trabajos_realizados TEXT",
                "ALTER TABLE quotes ADD COLUMN IF NOT EXISTS version_num INTEGER NOT NULL DEFAULT 1",
                "ALTER TABLE quotes ADD COLUMN IF NOT EXISTS origen_quote_id INTEGER NULL",
                f"ALTER TABLE quotes ADD COLUMN IF NOT EXISTS fecha_rechazado {dt_type}",
                "ALTER TABLE quotes ADD COLUMN IF NOT EXISTS rechazo_comentario TEXT",
                "ALTER TABLE quote_items ADD COLUMN IF NOT EXISTS repuesto_id INTEGER",
                "ALTER TABLE quote_items ADD COLUMN IF NOT EXISTS repuesto_codigo TEXT",
                "ALTER TABLE quote_items ADD COLUMN IF NOT EXISTS costo_u_neto NUMERIC",
                "ALTER TABLE ingreso_tests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ",
                "ALTER TABLE ingreso_media ADD COLUMN IF NOT EXISTS storage_path TEXT",
                "ALTER TABLE ingreso_media ADD COLUMN IF NOT EXISTS thumbnail_path TEXT",
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_id INTEGER",
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS role TEXT",
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS method TEXT",
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS path TEXT",
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS ip TEXT",
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_agent TEXT",
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS status_code INTEGER",
                f"ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS body {json_type}",
                "ALTER TABLE notification_user_preferences ADD COLUMN IF NOT EXISTS user_id INTEGER",
                "ALTER TABLE notification_user_preferences ADD COLUMN IF NOT EXISTS notification_key TEXT",
                "ALTER TABLE notification_user_preferences ADD COLUMN IF NOT EXISTS enabled BOOLEAN",
            ):
                try:
                    cur.execute(ddl)
                except Exception:
                    connection.rollback()
                    pass

        super().setUpClass()

    @classmethod
    def setUpTestData(cls):
        cls._seed()

    @classmethod
    def _seed(cls):
        now = timezone.now()
        with connection.cursor() as cur:
            for table in (
                "equipos_derivados",
                "bejerman_article_mappings",
                "ingreso_media",
                "ingreso_tests",
                "quote_items",
                "quotes",
                "notifications",
                "ingreso_events",
                "ingresos",
                "devices",
                "users",
                "locations",
                "models",
                "marcas",
                "customers",
            ):
                cur.execute(f"DELETE FROM {table}")

            cur.execute("INSERT INTO customers (id, razon_social) VALUES (%s, %s), (%s, %s)", [1, "Cliente A", 2, "Cliente B"])
            cur.execute("INSERT INTO marcas (id, nombre) VALUES (%s, %s)", [1, "Marca"])
            cur.execute(
                "INSERT INTO models (id, marca_id, nombre, tipo_equipo, variante) VALUES (%s, %s, %s, %s, %s)",
                [1, 1, "Modelo X", "Monitor", ""],
            )
            cur.execute(
                """
                INSERT INTO bejerman_article_mappings (
                    id, model_id, variante, variante_norm, article_code, article_description, match_source
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                [1, 1, "", "", "11", "Liberacion servicio tecnico", "manual"],
            )
            cur.execute("INSERT INTO locations (id, nombre) VALUES (%s, %s), (%s, %s)", [1, "Taller", 2, "Deposito"])
            cur.execute(
                """
                INSERT INTO users (id, nombre, email, hash_pw, rol, activo)
                VALUES
                  (%s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s)
                """,
                [
                    7, "Tecnico Uno", "t@example.com", "", "tecnico", True,
                    8, "Jefe Uno", "jefe@example.com", "", "jefe", True,
                    9, "Veedor Uno", "veedor@example.com", "", "jefe_veedor", True,
                ],
            )
            cur.execute(
                """
                INSERT INTO devices (id, customer_id, marca_id, model_id, numero_serie, numero_interno, variante)
                VALUES
                  (%s, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s)
                """,
                [
                    10, 1, 1, 1, "SER-A", "MG-A", "",
                    11, 1, 1, 1, "SER-B", "MG-B", "",
                    12, 2, 1, 1, "SER-C", "MG-C", "",
                    13, 1, 1, 1, "SER-D", "MG-D", "",
                ],
            )
            rows = [
                (100, 10, "diagnostico", "pendiente", "reparacion", now - timedelta(days=2), now - timedelta(days=2), None, 1, None, "", "", "", ""),
                (101, 11, "entregado", "emitido", "reparacion", now - timedelta(days=4), now - timedelta(days=4), None, 1, None, "", "", "", ""),
                (102, 12, "diagnostico", "pendiente", "reparacion", now - timedelta(days=18), now - timedelta(days=18), None, 1, None, "", "", "", ""),
                (103, 13, "diagnostico", "pendiente", "reparacion", now - timedelta(days=1), now - timedelta(days=1), None, 2, None, "", "", "", ""),
                (
                    104,
                    10,
                    "reparacion",
                    "emitido",
                    "urgente control",
                    now - timedelta(days=8),
                    now - timedelta(days=8),
                    None,
                    1,
                    7,
                    "",
                    "Informe preliminar",
                    "Falla de calibracion detectada",
                    "Reemplazo y ajuste del modulo de medicion",
                ),
            ]
            for row in rows:
                cur.execute(
                    """
                    INSERT INTO ingresos (
                        id, device_id, estado, presupuesto_estado, motivo, fecha_ingreso, fecha_creacion,
                        fecha_servicio, ubicacion_id, asignado_a, equipo_variante, informe_preliminar,
                        descripcion_problema, trabajos_realizados
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    row,
                )
            cur.execute("UPDATE ingresos SET resolucion=%s WHERE id=%s", ["no_reparado", 100])
            cur.execute(
                """
                INSERT INTO quotes (
                    id, ingreso_id, estado, subtotal, iva_21, total, moneda, fecha_emitido,
                    fecha_aprobado, autorizado_por, forma_pago, plazo_entrega_txt, garantia_txt,
                    mant_oferta_txt, pdf_url
                )
                VALUES
                  (%s, %s, %s, %s, %s, %s, %s, %s, NULL, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s, %s, NULL, %s, %s, %s, %s, %s, %s)
                """,
                [
                    1, 104, "presupuestado", 100, 21, 121, "ARS", now - timedelta(days=1),
                    "Cliente", "30 F.F.", "5 dias", "90 dias", "7 dias", "/api/quotes/104/pdf/",
                    2, 102, "presupuestado", 200, 42, 242, "ARS", now - timedelta(days=1),
                    "Cliente", "30 F.F.", "5 dias", "90 dias", "7 dias", "/api/quotes/102/pdf/",
                ],
            )
            cur.execute(
                """
                INSERT INTO quote_items (id, quote_id, tipo, descripcion, qty, precio_u, costo_u_neto)
                VALUES
                  (%s, %s, %s, %s, %s, %s, %s),
                  (%s, %s, %s, %s, %s, %s, %s)
                """,
                [
                    1, 1, "repuesto", "Filtro", 1, 80, 10,
                    2, 1, "mano_obra", "Mano de obra", 1, 20, 0,
                ],
            )
            references = [{"ref_id": "REF-01", "titulo": "ISO 80601-2-69:2020"}]
            schema = {
                "template_key": "concentrador_oxigeno_v1",
                "template_version": "1.0.0",
                "display_name": "Concentrador de oxigeno",
                "references": references,
                "sections": [],
                "result_options": [],
                "global_result_options": [],
            }
            cur.execute(
                """
                INSERT INTO ingreso_tests (
                    ingreso_id, template_key, template_version, tipo_equipo_snapshot,
                    payload, schema_snapshot, references_snapshot, resultado_global,
                    conclusion, instrumentos, firmado_por, fecha_ejecucion, tecnico_id,
                    created_at, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                [
                    100,
                    "concentrador_oxigeno_v1",
                    "1.0.0",
                    "Concentrador de oxigeno",
                    json.dumps({"values": {}}),
                    json.dumps(schema),
                    json.dumps(references),
                    "apto",
                    "Equipo apto",
                    "Analizador O2",
                    "Tecnico Uno",
                    now,
                    7,
                    now,
                    now,
                ],
            )
            cur.execute(
                """
                INSERT INTO ingreso_media (
                    id, ingreso_id, usuario_id, comentario, mime_type, size_bytes,
                    width, height, original_name, storage_path, thumbnail_path, created_at, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                [1, 100, 7, "Frente del equipo", "image/jpeg", 1234, 640, 480, "frente.jpg", "missing/frente.jpg", "missing/frente-thumb.jpg", now, now],
            )

    def setUp(self):
        self.client = APIClient()

    def _auth(self):
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {PORTAL_TOKEN}")

    def test_missing_or_invalid_token_returns_401(self):
        response = self.client.get("/api/integrations/portal/clientes/1/general/")
        self.assertEqual(response.status_code, 401)

        self.client.credentials(HTTP_AUTHORIZATION="Bearer wrong")
        response = self.client.get("/api/integrations/portal/clientes/1/general/")
        self.assertEqual(response.status_code, 401)

    @override_settings(PORTAL_INTEGRATION_ALLOWED_IPS=["100.64.0.0/10"])
    def test_ip_allowlist_is_enforced_when_configured(self):
        self._auth()
        response = self.client.get(
            "/api/integrations/portal/clientes/1/general/",
            REMOTE_ADDR="127.0.0.1",
        )

        self.assertEqual(response.status_code, 401)

    def test_client_general_uses_nexora_general_rules(self):
        self._auth()
        response = self.client.get("/api/integrations/portal/clientes/1/general/")

        self.assertEqual(response.status_code, 200)
        ids = {item["nexoraIngresoId"] for item in response.data["items"]}
        self.assertEqual(ids, {100, 104})
        self.assertTrue(all(item["companyName"] == "Cliente A" for item in response.data["items"]))

    def test_client_summary_does_not_cross_customer_boundary(self):
        self._auth()
        response = self.client.get("/api/integrations/portal/clientes/2/ingresos/100/summary/")

        self.assertEqual(response.status_code, 404)

    def test_ingreso_summary_exposes_test_and_media_for_portal(self):
        self._auth()
        response = self.client.get("/api/integrations/portal/clientes/1/ingresos/100/summary/")

        self.assertEqual(response.status_code, 200)
        item = response.data["item"]
        self.assertEqual(item["technicalReport"]["result"], "apto")
        self.assertTrue(item["technicalReport"]["pdfAvailable"])
        self.assertEqual(item["technicalReport"]["templateKey"], "concentrador_oxigeno_v1")
        self.assertEqual(len(item["mediaItems"]), 1)
        self.assertEqual(item["mediaItems"][0]["originalName"], "frente.jpg")
        self.assertEqual(item["serviceResolution"], "no_reparado")
        self.assertEqual(item["resolucion"], "no_reparado")
        self.assertEqual(item["bejermanArticleCode"], "11")
        self.assertEqual(item["bejermanArticleName"], "Liberacion servicio tecnico")

        internal = self.client.get("/api/integrations/portal/internal/ingresos/100/summary/")
        self.assertEqual(internal.status_code, 200)
        self.assertEqual(internal.data["item"]["technicalReport"]["result"], "apto")
        self.assertEqual(internal.data["item"]["bejermanArticleCode"], "11")

    def test_test_pdf_proxy_respects_customer_boundary(self):
        self._auth()
        response = self.client.get("/api/integrations/portal/clientes/1/ingresos/100/test/pdf/")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/pdf")

        blocked = self.client.get("/api/integrations/portal/clientes/2/ingresos/100/test/pdf/")
        self.assertEqual(blocked.status_code, 404)

    def test_client_budgets_do_not_cross_customer_boundary_and_hide_costs(self):
        self._auth()
        response = self.client.get("/api/integrations/portal/clientes/1/presupuestos/")

        self.assertEqual(response.status_code, 200)
        ids = {item["nexoraIngresoId"] for item in response.data["items"]}
        self.assertEqual(ids, {104})
        self.assertEqual(response.data["items"][0]["status"], "Presupuestado")

        detail = self.client.get("/api/integrations/portal/clientes/1/presupuestos/104/summary/")
        self.assertEqual(detail.status_code, 200)
        self.assertEqual(detail.data["item"]["diagnosis"], "Falla de calibracion detectada")
        self.assertEqual(detail.data["item"]["workToDo"], "Reemplazo y ajuste del modulo de medicion")
        self.assertEqual(detail.data["item"]["items"][0]["description"], "Filtro")
        self.assertNotIn("costo_u_neto", detail.data["item"]["items"][0])
        self.assertNotIn("unitPrice", detail.data["item"]["items"][0])
        self.assertNotIn("subtotal", detail.data["item"]["items"][0])

        blocked = self.client.get("/api/integrations/portal/clientes/2/presupuestos/104/summary/")
        self.assertEqual(blocked.status_code, 404)

    def test_budget_reject_requires_reason(self):
        self._auth()
        response = self.client.post(
            "/api/integrations/portal/clientes/1/presupuestos/104/decision/",
            {"decision": "reject"},
            format="json",
        )

        self.assertEqual(response.status_code, 400)

    def test_budget_reject_updates_quote_ingreso_and_notifies_only_jefe(self):
        self._auth()
        response = self.client.post(
            "/api/integrations/portal/clientes/1/presupuestos/104/decision/",
            {"decision": "reject", "reason": "No autorizado por compras"},
            format="json",
            HTTP_X_PORTAL_USER_EMAIL="compras@cliente.test",
            HTTP_X_PORTAL_CLIENT_IP="203.0.113.10",
            HTTP_X_PORTAL_USER_AGENT="PortalBrowser/1.0",
        )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["item"]["status"], "Rechazado")
        with connection.cursor() as cur:
            cur.execute("SELECT estado, fecha_rechazado, rechazo_comentario FROM quotes WHERE id=%s", [1])
            quote_row = cur.fetchone()
            cur.execute("SELECT presupuesto_estado FROM ingresos WHERE id=%s", [104])
            ingreso_row = cur.fetchone()
            cur.execute("SELECT user_id, notification_key, payload FROM notifications ORDER BY user_id")
            notifications = cur.fetchall()

        self.assertEqual(quote_row[0], "rechazado")
        self.assertIsNotNone(quote_row[1])
        self.assertEqual(quote_row[2], "No autorizado por compras")
        self.assertEqual(ingreso_row[0], "rechazado")
        self.assertEqual([row[0] for row in notifications], [8])
        self.assertEqual(notifications[0][1], "presupuesto_decision_portal")
        self.assertIn("203.0.113.10", str(notifications[0][2]))
        self.assertIn("PortalBrowser/1.0", str(notifications[0][2]))

    def test_budget_approve_updates_quote_ingreso_and_rejects_second_decision(self):
        self._auth()
        response = self.client.post(
            "/api/integrations/portal/clientes/1/presupuestos/104/decision/",
            {"decision": "approve"},
            format="json",
            HTTP_X_PORTAL_USER_EMAIL="compras@cliente.test",
        )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["item"]["status"], "Aprobado")
        with connection.cursor() as cur:
            cur.execute("SELECT estado FROM quotes WHERE id=%s", [1])
            self.assertEqual(cur.fetchone()[0], "aprobado")
            cur.execute("SELECT presupuesto_estado FROM ingresos WHERE id=%s", [104])
            self.assertEqual(cur.fetchone()[0], "aprobado")

        second = self.client.post(
            "/api/integrations/portal/clientes/1/presupuestos/104/decision/",
            {"decision": "reject", "reason": "Tarde"},
            format="json",
        )
        self.assertEqual(second.status_code, 409)

    def test_internal_queue_respects_workshop_and_terminal_filters(self):
        self._auth()
        response = self.client.get(
            "/api/integrations/portal/internal/work-queue/?companyId=1&assignedUserId=unassigned&page=1&pageSize=10"
        )

        self.assertEqual(response.status_code, 200)
        ids = [item["nexoraIngresoId"] for item in response.data["items"]]
        self.assertEqual(ids, [100])
        self.assertEqual(response.data["items"][0]["bejermanArticleCode"], "11")
        self.assertEqual(response.data["items"][0]["serviceResolution"], "no_reparado")
        self.assertEqual(response.data["pagination"]["totalItems"], 1)

    def test_internal_queue_ready_filter_includes_liberados_from_listos(self):
        self._auth()
        now = timezone.now()
        with connection.cursor() as cur:
            cur.execute(
                "INSERT INTO devices (id, customer_id, marca_id, model_id, numero_serie, numero_interno, variante) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                [14, 1, 1, 1, "SER-LIB", "A2-0187", ""],
            )
            cur.execute(
                """
                INSERT INTO ingresos (
                    id, device_id, estado, presupuesto_estado, motivo, fecha_ingreso, fecha_creacion,
                    fecha_servicio, ubicacion_id, asignado_a, equipo_variante, informe_preliminar,
                    descripcion_problema, trabajos_realizados
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                [105, 14, "liberado", "no_aplica", "reparacion", now, now, now, 1, None, "", "", "", ""],
            )
            cur.execute(
                "INSERT INTO ingreso_events (ingreso_id, a_estado, ts) VALUES (%s, %s, %s)",
                [105, "liberado", now],
            )

        response = self.client.get(
            "/api/integrations/portal/internal/work-queue/?status=Listo%20para%20Entrega&search=A2-0187&page=1&pageSize=10"
        )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["pagination"]["totalItems"], 1)
        item = response.data["items"][0]
        self.assertEqual(item["nexoraIngresoId"], 105)
        self.assertEqual(item["equipoInternalNumber"], "A2-0187")
        self.assertEqual(item["bejermanArticleCode"], "11")
        self.assertTrue(item["releasedForDelivery"])
        self.assertIsNotNone(item["releasedAt"])
